Vagrant.configure(2) do |configs|
	configs.vm.define "aulos", autostart: true do |config|

		config.vm.box = "ubuntu/focal64"
		config.vm.box_check_update = true

                config.vm.network "forwarded_port", guest: 1883, host: 1883  # mosquitto
                config.vm.network "forwarded_port", guest: 3306, host: 3306  # mariadb
		config.vm.network "forwarded_port", guest: 8080, host: 8080  # keycloak

		config.vm.provider "virtualbox" do |vb|
			vb.name = "Keycloak"
			vb.memory = 1024
		end

		config.vm.provision "shell", privileged: true, binary: true, :inline => <<-SHELL
                        export DEBIAN_FRONTEND=noninteractive
                        sudo apt-get update
                        sudo apt-get install mosquitto mariadb-server -y
                        mysql -e "CREATE DATABASE aulos;"
                        mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' IDENTIFIED BY 'admin' WITH GRANT OPTION;"
                        mysql -e "GRANT ALL PRIVILEGES ON aulos.* TO 'aulos'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
                        cat /vagrant/aulos.sql | mysql aulos
                        sed -i -r 's/bind-address.*/bind-address=0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf
                        systemctl restart mariadb

                        source <(tr -d '\r' < /vagrant/init-keycloak.sh)
		SHELL
	end
end

